### ISSUE TITLE
[Question] What is the status of this repository?

### ISSUE THREAD

**Issue by phamnhuvu-dev** [google/hierarchical-state-machine.dart#1]
Thank you for your contribution.
I intend to use HSM for our applications, but I am not sure if this repository is still being developed or is alive.

**Comment by jtmcdole** [comment]
It's alive; it's just being used in projects. There hasn't really been a need to update it - or better put, upgrading the library might make some projects that depended on the internals of the machine brittle.

**Comment by jtmcdole** [comment]
Note; I've published from: https://github.com/jtmcdole/hierarchical-state-machine.dart
